<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see screenshot: <br/>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_43_IST_2022.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br/>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_43_IST_2022.jpg><img src=Mon_Feb_28_19_20_43_IST_2022.jpg height=300 width=300 /></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot: <br/>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_44_IST_2022.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br/>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_44_IST_2022.jpg><img src=Mon_Feb_28_19_20_44_IST_2022.jpg height=300 width=300 /></a>]]>
    </line>
    <line>
      <![CDATA[Click to see screenshot: <br/>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_45_IST_2022.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br/>]]>
    </line>
    <line>
      <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_45_IST_2022.jpg><img src=Mon_Feb_28_19_20_45_IST_2022.jpg height=300 width=300 /></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2022-02-28T13:50:42Z" name="Data Driven Basics" finished-at="2022-02-28T13:50:46Z" duration-ms="3883">
    <groups>
    </groups>
    <test started-at="2022-02-28T13:50:42Z" name="Bank Manager Login Test" finished-at="2022-02-28T13:50:44Z" duration-ms="1894">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@60129b9a]" started-at="2022-02-28T13:50:42Z" name="loginAsBankManager" finished-at="2022-02-28T13:50:43Z" duration-ms="1131" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not succesfull]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not succesfull
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot: <br/>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_43_IST_2022.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br/>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_43_IST_2022.jpg><img src=Mon_Feb_28_19_20_43_IST_2022.jpg height=300 width=300 /></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test started-at="2022-02-28T13:50:44Z" name="Add Customer Test" finished-at="2022-02-28T13:50:46Z" duration-ms="1914">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.w2a.testcases.AddCustomerTest@5f9be66c]" started-at="2022-02-28T13:50:39Z" name="setUP" finished-at="2022-02-28T13:50:42Z" duration-ms="2170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@5f9be66c]" started-at="2022-02-28T13:50:44Z" name="addCustomer" data-provider="getData" finished-at="2022-02-28T13:50:44Z" duration-ms="648" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sandip]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[thopate]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[hsf894r]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added successfully
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot: <br/>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_44_IST_2022.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br/>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_44_IST_2022.jpg><img src=Mon_Feb_28_19_20_44_IST_2022.jpg height=300 width=300 /></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@5f9be66c]" started-at="2022-02-28T13:50:45Z" name="addCustomer" data-provider="getData" finished-at="2022-02-28T13:50:45Z" duration-ms="347" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[lasdjf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lslsjf]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[567898.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added successfully
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see screenshot: <br/>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_45_IST_2022.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br/>]]>
            </line>
            <line>
              <![CDATA[<a target="blank" href=Mon_Feb_28_19_20_45_IST_2022.jpg><img src=Mon_Feb_28_19_20_45_IST_2022.jpg height=300 width=300 /></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.w2a.testcases.AddCustomerTest@5f9be66c]" started-at="2022-02-28T13:50:46Z" name="tearDown" finished-at="2022-02-28T13:50:46Z" duration-ms="164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
